java_test(
    name = "my_activity_test",
    srcs = [
        "MyActivityTest.java",
    ],
    deps = [
        "@robolectric//:default",
    ],
    visibility = [
        "//visibility:public"
    ]
)
