/*
 * This file is experimental and not a functional robolectric test.
 * It is present primarily to test the import statements
 * (from the maven_repository rule).
 */
package example.activity;

import android.app.Activity;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

//import example.activity.BuildConfig;
//import example.activity.R;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.Robolectric;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;

import static org.hamcrest.Matchers.equalTo;
import static org.junit.Assert.assertThat;


@RunWith(RobolectricTestRunner.class)
@Config()
//@Config(constants = BuildConfig.class)
public class MyActivityTest {

  @Test
  public void clickingButton_shouldChangeResultsViewText() throws Exception {
    Activity activity = Robolectric.setupActivity(MyActivity.class);

    Button button = (Button) activity.findViewById(R.id.host_edit_text);
    TextView results = (TextView) activity.findViewById(R.id.rpc_response_text);

    button.performClick();
    assertThat(results.getText().toString(), equalTo("Foo!"));
  }

  // Copied into the
  /* AUTO-GENERATED FILE.  DO NOT MODIFY.
   *
   * This class was automatically generated by the aapt tool from the
   * resource data it found.  It should not be modified by hand.
   */

  public static final class R {
    public static final class attr {
    }
    public static final class id {
      public static int host_edit_text=0x7f030000;
      public static int message_edit_text=0x7f030002;
      public static int port_edit_text=0x7f030001;
      public static int rpc_response_text=0x7f030004;
      public static int send_button=0x7f030003;
    }
    public static final class layout {
      public static int activity_main=0x7f020000;
    }
  }

}
